CREATE DATABASE IF NOT EXISTS Gerente
WITH ENCODING = 'UTF8';

USE Gerente;

CREATE TABLE IF NOT EXISTS DadosGerente (
    GerenteID INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    CPF VARCHAR(12) UNIQUE NOT NULL,
    Telefone VARCHAR(15)
);
